import Head from 'next/head';
import { useState, useEffect, ChangeEvent } from 'react';
// import { createProduct } from '../api/apiAll';
import api from '../api/apiAll';

export default function CraeteProduct () {

  const [img, setImg] = useState<File | null>(null);
  const [name, setName] = useState("");
  const [price, setPrice] = useState(0);
  const [desc, setDesc] = useState("");
  const [userId, setUserId] = useState(0);
  const [status, setStatus] = useState(true);
  const [product, setProduct] = useState({});

  const handleImageChange = (event: ChangeEvent<HTMLInputElement>) => {
    event.preventDefault()
    if(event.target.files === null) return
    const file = event.target.files[0];
    setImg(file);
  }

  const handleSubmit = async (e: any) => {
    e.preventDefault();
    const formData = new FormData();
    formData.append('name', name);
    formData.append('price', price.toString());
    formData.append('desc', desc);
    formData.append('status', status.toString());
    formData.append('userId', userId.toString());
    formData.append('img', img!);

    const headers = {
      'headers': {
        'Content-Type': 'multipart/form-data'
      }
    }
    await api.post("/products", formData, headers)
    .then((response) => {
      console.log(response)
    }).catch((err) => {
      if(err.response) {
        console.log(err.response);
      } else {
        console.log("ERR: Tente mais tarde!")
      }
    })
    
    setName("");
    setImg(null);
    setPrice(0);
    setDesc("");
    setUserId(0);
  };
  
    return (
        <div className="">
            <Head>
                <title>New product</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1 className="font-bold">Iniciando o projeto</h1>
                <form onSubmit={handleSubmit} method="post" encType="multipart/form-data">
                <label>
                    Nome         
                    <input type="text" name="name" value={name} onChange={(e) => setName(e.target.value)} /><br/>
                </label>
                <label>
                    Price         
                    <input type="number" name="price" value={price} onChange={(e) => setPrice(parseFloat(e.target.value))} /><br/>
                </label>
                <label>
                    Descrião         
                    <textarea name="desc" value={desc} onChange={(e) => setDesc(e.target.value)} /><br/>
                </label>
                <label>
                    Imagem
                    <input type="file" name="img" accept="image/png, image/jpeg" onChange={handleImageChange} />
                </label>
                <label>
                    status
                    <input type="checkbox" name="status" checked={status} onChange={(e) => setStatus(e.target.checked)} /><br/>
                </label>
                <label>
                    UserId
                    <input type="number" name="userId" value={userId} onChange={(e) => setUserId(parseInt(e.target.value))} /><br/>
                </label>
                <br /><br />
                <button type="submit">Salvar</button>
                </form>
            </main>
        </div>
    );
}